### ISSUE TITLE
Allow run in addition to emulate

### ISSUE THREAD

**Issue by dariosalvi78** [ryscheng/karma-cordova-launcher#4]
Hi, thanks for this very cool plugin!

One simple thing, though, would make it even more useful: instead of just emulating, also use the "run" mode. The Android emulator is known to be horribly slow, and things like Genymotion allow a much faster interaction, but they work as pseudo-real devices. In addition, in some scenarios you would also prefer a physical device instead of emulated ones.

The change is minimal: in index.js, line 97, instead of using a fixed word "emulate", it would be good to have a parameter from the settings that can be either "emulate" or "run".
Also, as Genymotion or real devices don't use the standard loopback address 10.0.2.2, on line 65, we would need to specify a different address (10.0.3.2 for Genymotion for example). Again, the address could be set in the settings of the plugin. I could clone this project and make the changes myself, but it would be nice if these are done "officially" in your repository.

Cheers.

**Comment by ryscheng** [comment]
This is a great idea! I agree that these would be great options to add. If you write up a pull request, I would happily review it and publish a new version for you.
Thanks for the interest!

**Comment by dariosalvi78** [comment]
done, thanks!
