### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by cheskos** [ryscheng/karma-cordova-launcher#8]
Hello.

I am trying to setup karma in order to unit test my cordova/ionic hybrid app, and I'm getting errors due to plugins not working, specifically, I'm getting undefined errors with cordova-plugin-network-information. Your documentation states that plugins should be written using a namespace (?) syntax, such as 

> 'org.apache.cordova.console'

which I personally find odd since during the time I've worked with hybrid apps and cordova plugins everyone uses the dashes syntax:

> 'cordova-plugin-console',

If the former syntax is the right one, how are we supposed to find out or get the correct plugin names if everyone uses the latter?

Thanks

**Comment by ryscheng** [comment]
@janus-toendering could I enlist your help in updating this?

**Comment by janus-toendering** [comment]
Yeah I will have a look later. Currently trying to improve the Cordova package to help support some use cases I have.

**Comment by ryscheng** [comment]
Great thanks!

**Comment by ryscheng** [comment]
https://github.com/ryscheng/karma-cordova-launcher/pull/13
